language: go

os:
- linux
- osx

go:
- 1.8
- tip

matrix:
  allow_failures:
  - go: tip

install:
- sudo apt-get -qq update
- sudo apt-get install libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev mesa-common-dev libgl1-mesa-dev libxxf86vm-dev
- go get -t -v -d ./...
- go install
